Repository DDang-Org/BackEnd, pull requests merged in 2025-02, with the labels that each got.

#27 feat : #26 전체적인 댕댕로그 조회로 전환
  src/main/java/com/ddang/dog/repository/DogRepository.java
  src/main/java/com/ddang/walk/controller/WalkLogController.java
  src/main/java/com/ddang/walk/repository/WalkDogRepository.java
  src/main/java/com/ddang/walk/service/WalkLogService.java
  src/main/java/com/ddang/walk/service/WalkLogServiceImpl.java
  src/test/java/com/ddang/walk/controller/WalkLogControllerTest.java
  src/test/java/com/ddang/walk/repository/WalkDogRepositoryTest.java
  src/test/java/com/ddang/walk/service/WalkLogServiceImplTest.java
Labels: ✨Feature, 문재경

#31 Feat/#30 websocket 설정
  build.gradle
  src/main/java/com/ddang/global/aop/AuthenticationContext.java
  src/main/java/com/ddang/global/aop/ExtractEmail.java
  src/main/java/com/ddang/global/aop/JwtAuthenticationAspect.java
  src/main/java/com/ddang/global/api/WebSocketResponse.java
  src/main/java/com/ddang/global/event/WebSocketMessageEvent.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/global/websocket/StompHandler.java
  src/main/java/com/ddang/global/websocket/WebSocketConfig.java
  src/main/java/com/ddang/member/jwt/service/JwtService.java
Labels: ✨Feature, 문재경

#28 [Feat/#10] 패밀리댕 재구현
  .github/workflows/sonarcloud.yaml
  src/main/java/com/ddang/dog/repository/DogRepository.java
  src/main/java/com/ddang/dog/repository/MemberDogRepository.java
  src/main/java/com/ddang/family/controller/FamilyController.java
  src/main/java/com/ddang/family/controller/request/FamilyJoinRequest.java
  src/main/java/com/ddang/family/entity/DayOfWeek.java
  src/main/java/com/ddang/family/entity/Family.java
  src/main/java/com/ddang/family/entity/WalkSchedule.java
  src/main/java/com/ddang/family/entity/WeekDay.java
  src/main/java/com/ddang/family/repository/FamilyRepository.java
  src/main/java/com/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/com/ddang/family/service/FamilyInviteCodeManager.java
  src/main/java/com/ddang/family/service/FamilyService.java
  src/main/java/com/ddang/family/service/FamilyServiceImpl.java
  src/main/java/com/ddang/family/service/response/FamilyDogResponse.java
  src/main/java/com/ddang/family/service/response/FamilyMemberResponse.java
  src/main/java/com/ddang/family/service/response/FamilyResponse.java
  src/main/java/com/ddang/family/service/response/InviteCodeResponse.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/member/repository/MemberRepository.java
  src/test/java/com/ddang/family/service/FamilyServiceImplTest.java
Labels: ✨Feature, 📃 Docs, 노관태

#35 feat : #34 MultiPart 데이터 Converter 추가
  src/main/java/com/ddang/global/config/MultipartJackson2HttpMessageConverter.java
Labels: ✨Feature, 문재경

#36 [Feat/#29] chat
  build.gradle
  src/main/java/com/ddang/chat/controller/ChatController.java
  src/main/java/com/ddang/chat/controller/ChatRoomController.java
  src/main/java/com/ddang/chat/controller/WebsocketChatController.java
  src/main/java/com/ddang/chat/controller/request/ChatMessageRequest.java
  src/main/java/com/ddang/chat/repository/ChatMemberRepository.java
  src/main/java/com/ddang/chat/repository/ChatRepository.java
  src/main/java/com/ddang/chat/repository/ChatRoomRepository.java
  src/main/java/com/ddang/chat/service/ChatKafkaListener.java
  src/main/java/com/ddang/chat/service/ChatKafkaProducer.java
  src/main/java/com/ddang/chat/service/ChatRoomService.java
  src/main/java/com/ddang/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/ddang/chat/service/ChatService.java
  src/main/java/com/ddang/chat/service/ChatServiceImpl.java
  src/main/java/com/ddang/chat/service/request/ChatMessageKafkaRequest.java
  src/main/java/com/ddang/chat/service/request/ChatMessageServiceRequest.java
  src/main/java/com/ddang/chat/service/response/ChatMemberInfo.java
  src/main/java/com/ddang/chat/service/response/ChatMessageResponse.java
  src/main/java/com/ddang/chat/service/response/ChatRoomResponse.java
  src/main/java/com/ddang/global/config/KafkaConfig.java
  src/main/java/com/ddang/global/controller/WebSocketController.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/global/websocket/WebSocketConfig.java
Labels: ✨Feature, 노관태

#37 Feat/#23 소셜 기능
  src/main/java/com/ddang/dog/controller/DogController.java
  src/main/java/com/ddang/dog/service/DogService.java
  src/main/java/com/ddang/dog/service/DogServiceImpl.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ddang/member/controller/FriendController.java
  src/main/java/com/ddang/member/controller/MemberController.java
  src/main/java/com/ddang/member/controller/request/AddFriendRequest.java
  src/main/java/com/ddang/member/repository/BlockRepository.java
  src/main/java/com/ddang/member/repository/FriendRepository.java
  src/main/java/com/ddang/member/repository/FriendRequestRepository.java
  src/main/java/com/ddang/member/service/FriendService.java
  src/main/java/com/ddang/member/service/FriendServiceImpl.java
  src/main/java/com/ddang/member/service/request/AddFriendServiceRequest.java
  src/main/java/com/ddang/member/service/response/FriendListResponse.java
  src/main/java/com/ddang/member/service/response/FriendResponse.java
  src/main/java/com/ddang/walk/service/WalkLogServiceImpl.java
  src/test/java/com/ddang/ApiTestSupport.java
  src/test/java/com/ddang/dog/controller/DogControllerTest.java
  src/test/java/com/ddang/dog/service/DogServiceImplTest.java
  src/test/java/com/ddang/member/controller/FriendControllerTest.java
  src/test/java/com/ddang/member/repostiory/FriendRepositoryTest.java
  src/test/java/com/ddang/member/service/FriendServiceImplTest.java
Labels: ✨Feature, 문재경

#40 Feat/#22 산책 API
  src/main/java/com/ddang/dog/entity/Dog.java
  src/main/java/com/ddang/dog/repository/DogRepository.java
  src/main/java/com/ddang/dog/repository/MemberDogRepository.java
  src/main/java/com/ddang/dog/service/response/DogResponse.java
  src/main/java/com/ddang/global/config/RedisConfig.java
  src/main/java/com/ddang/global/controller/WebSocketWalkController.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/global/service/RedisKey.java
  src/main/java/com/ddang/global/service/RedisService.java
  src/main/java/com/ddang/walk/controller/WalkController.java
  src/main/java/com/ddang/walk/controller/WalkLocationController.java
  src/main/java/com/ddang/walk/controller/request/CompleteWalkRequest.java
  src/main/java/com/ddang/walk/controller/request/DecisionWalkRequest.java
  src/main/java/com/ddang/walk/controller/request/ProposalWalkRequest.java
  src/main/java/com/ddang/walk/controller/request/StartWalkRequest.java
  src/main/java/com/ddang/walk/controller/request/WalkRequest.java
  src/main/java/com/ddang/walk/service/WalkLocationService.java
  src/main/java/com/ddang/walk/service/WalkLocationServiceImpl.java
  src/main/java/com/ddang/walk/service/WalkService.java
  src/main/java/com/ddang/walk/service/WalkServiceImpl.java
  src/main/java/com/ddang/walk/service/request/CompleteWalkServiceRequest.java
  src/main/java/com/ddang/walk/service/request/DecisionWalkServiceRequest.java
  src/main/java/com/ddang/walk/service/request/ProposalWalkServiceRequest.java
  src/main/java/com/ddang/walk/service/request/StartWalkServiceRequest.java
  src/main/java/com/ddang/walk/service/request/WalkServiceRequest.java
  src/main/java/com/ddang/walk/service/response/walk/CompleteWalkResponse.java
  src/main/java/com/ddang/walk/service/response/walk/DecisionWalkResponse.java
  src/main/java/com/ddang/walk/service/response/walk/MemberNearbyResponse.java
  src/main/java/com/ddang/walk/service/response/walk/ProposalWalkResponse.java
  src/main/java/com/ddang/walk/service/response/walk/Type.java
  src/main/java/com/ddang/walk/service/response/walk/WalkWithDogInfo.java
  src/main/java/com/ddang/walk/service/response/walk/WalkWithResponse.java
Labels: ✨Feature, 문재경

#42 Feat/#41 family 엔티티 변경에 따른 수정
  src/main/java/com/ddang/dog/repository/MemberDogRepository.java
  src/main/java/com/ddang/dog/service/DogServiceImpl.java
  src/main/java/com/ddang/walk/service/WalkLogServiceImpl.java
  src/test/java/com/ddang/dog/entity/DogTest.java
  src/test/java/com/ddang/dog/repository/DogRepositoryTest.java
  src/test/java/com/ddang/dog/repository/MemberDogRepositoryTest.java
  src/test/java/com/ddang/dog/service/DogServiceImplTest.java
  src/test/java/com/ddang/walk/repository/WalkDogRepositoryTest.java
  src/test/java/com/ddang/walk/service/WalkLogServiceImplTest.java
Labels: 🔥BugFix, 문재경

#44 test: member test 작성
  src/main/java/com/ddang/member/entity/Member.java
  src/test/java/com/ddang/member/controller/MemberControllerTest.java
  src/test/java/com/ddang/member/repository/MemberRepositoryTest.java
  src/test/java/com/ddang/member/service/MemberServiceImplTest.java
Labels: 🧪Test, 송경훈

#48 [Feat/#46] family info api mod
  src/main/java/com/ddang/family/service/FamilyServiceImpl.java
  src/main/java/com/ddang/family/service/response/FamilyMemberResponse.java
  src/main/java/com/ddang/walk/repository/WalkDogRepository.java
  src/main/java/com/ddang/walk/repository/WalkRepository.java
Labels: ✨Feature, 노관태

#54 fix : #53 proxy 문제로 Entity 내에서 비교 불가능에 따른 수정
  src/main/java/com/ddang/dog/service/DogServiceImpl.java
  src/main/java/com/ddang/family/repository/FamilyRepository.java
  src/main/java/com/ddang/member/entity/Member.java
Labels: 🔥BugFix, 문재경

#56 fix : #53 create Dog 에러 수정
  src/main/java/com/ddang/dog/service/DogServiceImpl.java
Labels: 🔥BugFix, 문재경

#58 fix: reissue 로직 수정
  src/main/java/com/ddang/member/controller/MemberController.java
  src/main/java/com/ddang/member/controller/request/ReissueRequest.java
  src/main/java/com/ddang/member/service/MemberService.java
  src/main/java/com/ddang/member/service/MemberServiceImpl.java
  src/test/java/com/ddang/member/controller/MemberControllerTest.java
  src/test/java/com/ddang/member/service/MemberServiceImplTest.java
Labels: ✨Feature, 송경훈

#49 Feat/#45 Walk 차단 로직
  src/main/java/com/ddang/global/service/RedisKey.java
  src/main/java/com/ddang/global/service/RedisService.java
  src/main/java/com/ddang/member/repository/BlockRepository.java
  src/main/java/com/ddang/member/service/BlockServiceImpl.java
  src/main/java/com/ddang/walk/service/WalkLocationServiceImpl.java
  src/main/java/com/ddang/walk/service/WalkServiceImpl.java
Labels: ✨Feature, 문재경

#60 feat : #59 중복 이메일 회원가입 제한
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/member/controller/MemberController.java
  src/main/java/com/ddang/member/repository/MemberRepository.java
  src/main/java/com/ddang/member/service/MemberServiceImpl.java
Labels: ✨Feature, 문재경

#63 Fix/#62 exist 쿼리문 수정
  src/main/java/com/ddang/member/repository/MemberRepository.java
  src/main/java/com/ddang/member/service/MemberServiceImpl.java
  src/test/java/com/ddang/dog/controller/DogControllerTest.java
  src/test/java/com/ddang/dog/repository/MemberDogRepositoryTest.java
  src/test/java/com/ddang/dog/service/DogServiceImplTest.java
  src/test/java/com/ddang/family/service/FamilyServiceImplTest.java
  src/test/java/com/ddang/member/controller/FriendControllerTest.java
  src/test/java/com/ddang/member/repostiory/FriendRepositoryTest.java
  src/test/java/com/ddang/member/service/FriendServiceImplTest.java
  src/test/java/com/ddang/walk/controller/WalkLogControllerTest.java
  src/test/java/com/ddang/walk/repository/WalkDogRepositoryTest.java
  src/test/java/com/ddang/walk/service/WalkLogServiceImplTest.java
Labels: 🔥BugFix, 문재경

#65 refactor : #64 yaml 파일 secret 내용 추가
  .github/workflows/cicd.yaml
Labels: 🔨Refactor, 문재경

#67 Fix/#66 GitHub action Fix
  .github/workflows/cicd.yaml
Labels: 🔥BugFix, 문재경

#69 Fix/#68 ci-cd Action 수정
  .github/workflows/cicd.yaml
Labels: 🔥BugFix, 문재경

#72 feat : #71 산책 완료시 데이터 삭제 못했을 경우 에러를 던지는 것을 로그로 변경
  src/main/java/com/ddang/global/service/RedisService.java
Labels: ✨Feature, 문재경
