Repository DDang-Org/BackEnd, pull requests merged in 2025-01, with the labels that each got.

#9 Feat#6 Spring Security + OAuth2 + JWT를 활용한 인증/인가 구현
  build.gradle
  src/main/java/com/ddang/DdangApplication.java
  src/main/java/com/ddang/global/config/RedisConfig.java
  src/main/java/com/ddang/global/config/SwaggerConfig.java
  src/main/java/com/ddang/global/config/security/CorsConfig.java
  src/main/java/com/ddang/global/config/security/SecurityConfig.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ddang/global/exception/MemberException.java
  src/main/java/com/ddang/global/exception/RedisException.java
  src/main/java/com/ddang/global/service/RedisService.java
  src/main/java/com/ddang/member/controller/MemberController.java
  src/main/java/com/ddang/member/controller/request/JoinRequest.java
  src/main/java/com/ddang/member/entity/Member.java
  src/main/java/com/ddang/member/jwt/filter/JwtAuthFilter.java
  src/main/java/com/ddang/member/jwt/service/JwtService.java
  src/main/java/com/ddang/member/oauth2/CustomOAuth2User.java
  src/main/java/com/ddang/member/oauth2/OAuth2Attributes.java
  src/main/java/com/ddang/member/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/ddang/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/ddang/member/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/ddang/member/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/ddang/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/ddang/member/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/ddang/member/repository/MemberRepository.java
  src/main/java/com/ddang/member/service/CookieService.java
  src/main/java/com/ddang/member/service/MemberService.java
  src/main/java/com/ddang/member/service/MemberServiceImpl.java
  src/main/java/com/ddang/member/service/request/JoinServiceRequest.java
  src/main/java/com/ddang/member/service/response/MemberResponse.java
  src/main/resources/application.properties
Labels: ✨Feature, 송경훈

#13 [Feat/#7] cicd 세팅
  .github/workflows/cicd.yaml
  Dockerfile
  src/main/java/com/ddang/global/exception/GlobalExceptionHandler.java
Labels: ✨Feature, 문재경

#12 [Feat/#8 강아지 기능 추가]
  build.gradle
  src/main/java/com/ddang/dog/controller/DogController.java
  src/main/java/com/ddang/dog/controller/request/CreateDogRequest.java
  src/main/java/com/ddang/dog/controller/request/UpdateDogRequest.java
  src/main/java/com/ddang/dog/entity/Dog.java
  src/main/java/com/ddang/dog/repository/DogRepository.java
  src/main/java/com/ddang/dog/repository/MemberDogRepository.java
  src/main/java/com/ddang/dog/service/DogService.java
  src/main/java/com/ddang/dog/service/DogServiceImpl.java
  src/main/java/com/ddang/dog/service/request/CreateDogServiceRequest.java
  src/main/java/com/ddang/dog/service/request/UpdateDogServiceRequest.java
  src/main/java/com/ddang/dog/service/response/DogResponse.java
  src/main/java/com/ddang/family/entity/Family.java
  src/main/java/com/ddang/family/repository/FamilyRepository.java
  src/main/java/com/ddang/family/repository/WalkScheduleRepository.java
  src/main/java/com/ddang/global/api/ApiResponse.java
  src/main/java/com/ddang/global/config/S3Config.java
  src/main/java/com/ddang/global/config/SwaggerConfig.java
  src/main/java/com/ddang/global/exception/BadRequestException.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/global/exception/ErrorResponse.java
  src/main/java/com/ddang/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ddang/global/exception/SwaggerExampleHolder.java
  src/main/java/com/ddang/global/exception/annotation/SwaggerExceptionResponse.java
  src/main/java/com/ddang/global/service/S3Service.java
  src/main/java/com/ddang/member/entity/Member.java
  src/main/java/com/ddang/member/repository/MemberRepository.java
  src/test/java/com/ddang/ApiTestSupport.java
  src/test/java/com/ddang/IntegrationTestSupport.java
  src/test/java/com/ddang/dog/entity/DogTest.java
  src/test/java/com/ddang/dog/repository/DogRepositoryTest.java
  src/test/java/com/ddang/dog/repository/MemberDogRepositoryTest.java
  src/test/java/com/ddang/dog/service/DogServiceImplTest.java
Labels: ✨Feature, 문재경

#16 fix : #15 dto 변경
  src/main/java/com/ddang/dog/entity/Dog.java
Labels: 🔥BugFix, 문재경

#18 fix : #17 에러 나는 코드 수정
  src/main/java/com/ddang/global/config/SwaggerConfig.java
Labels: 🔥BugFix, 문재경

#21 [Feat/#14] 댕댕로그
  src/main/java/com/ddang/dog/controller/DogController.java
  src/main/java/com/ddang/dog/repository/MemberDogRepository.java
  src/main/java/com/ddang/dog/service/DogService.java
  src/main/java/com/ddang/dog/service/DogServiceImpl.java
  src/main/java/com/ddang/dog/service/response/DogWalkResponse.java
  src/main/java/com/ddang/global/api/ApiResponse.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/global/exception/NotFoundException.java
  src/main/java/com/ddang/walk/controller/WalkLogController.java
  src/main/java/com/ddang/walk/entity/Walk.java
  src/main/java/com/ddang/walk/repository/WalkDogRepository.java
  src/main/java/com/ddang/walk/service/WalkLogService.java
  src/main/java/com/ddang/walk/service/WalkLogServiceImpl.java
  src/main/java/com/ddang/walk/service/response/TimeDuration.java
  src/main/java/com/ddang/walk/service/response/log/WalkLogByFamilyResponse.java
  src/main/java/com/ddang/walk/service/response/log/WalkLogResponse.java
  src/main/java/com/ddang/walk/service/response/log/WalkStaticsResponse.java
  src/main/java/com/ddang/walk/util/DateCalculator.java
  src/main/java/com/ddang/walk/util/WalkCalculator.java
  src/test/java/com/ddang/ApiTestSupport.java
  src/test/java/com/ddang/dog/controller/DogControllerTest.java
  src/test/java/com/ddang/dog/repository/MemberDogRepositoryTest.java
  src/test/java/com/ddang/dog/service/DogServiceImplTest.java
  src/test/java/com/ddang/walk/controller/WalkLogControllerTest.java
  src/test/java/com/ddang/walk/repository/WalkDogRepositoryTest.java
  src/test/java/com/ddang/walk/service/WalkLogServiceImplTest.java
Labels: ✨Feature, 문재경

#24 [Feat#20] 차단, 알림 API 구현
  src/main/java/com/ddang/global/exception/BlockException.java
  src/main/java/com/ddang/global/exception/ErrorCode.java
  src/main/java/com/ddang/global/exception/NotificationException.java
  src/main/java/com/ddang/member/controller/BlockController.java
  src/main/java/com/ddang/member/controller/MemberController.java
  src/main/java/com/ddang/member/controller/request/JoinRequest.java
  src/main/java/com/ddang/member/entity/Block.java
  src/main/java/com/ddang/member/repository/BlockRepository.java
  src/main/java/com/ddang/member/repository/WalkWithMemberRepository.java
  src/main/java/com/ddang/member/service/BlockService.java
  src/main/java/com/ddang/member/service/BlockServiceImpl.java
  src/main/java/com/ddang/member/service/MemberServiceImpl.java
  src/main/java/com/ddang/member/service/response/BlockListResponse.java
  src/main/java/com/ddang/member/service/response/BlockResponse.java
  src/main/java/com/ddang/notification/controller/NotificationController.java
  src/main/java/com/ddang/notification/controller/NotificationSettingsController.java
  src/main/java/com/ddang/notification/controller/request/NotificationSettingsRequest.java
  src/main/java/com/ddang/notification/entity/NotificationSettings.java
  src/main/java/com/ddang/notification/repository/NotificationRepository.java
  src/main/java/com/ddang/notification/repository/NotificationSettingsRepository.java
  src/main/java/com/ddang/notification/service/NotificationService.java
  src/main/java/com/ddang/notification/service/NotificationServiceImpl.java
  src/main/java/com/ddang/notification/service/NotificationSettingsService.java
  src/main/java/com/ddang/notification/service/NotificationSettingsServiceImpl.java
  src/main/java/com/ddang/notification/service/response/NotificationResponse.java
  src/main/java/com/ddang/notification/service/response/SettingsResponse.java
  src/main/java/com/ddang/notification/service/response/SettingsUpdateResponse.java
  src/main/java/com/ddang/walk/repository/WalkRepository.java
Labels: ✨Feature, 송경훈
